<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SupFile.Back.Core\SupFile.Back.Core.csproj"/>
        <ProjectReference Include="..\SupFile.Back.Data\SupFile.Back.Data.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentEmail.Razor" Version="3.0.2"/>
        <PackageReference Include="FluentEmail.Smtp" Version="3.0.2"/>
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.7.0"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0"/>
    </ItemGroup>

</Project>
