services:
  supfile.api:
    image: supfile.back.api
    pull_policy: build
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: SupFile.Back.Api/Dockerfile
    networks:
      - supfileback_default
    depends_on:
      postgres:
        condition: service_healthy
      smtp4dev:
        condition: service_started
    ports:
      - "5263:5263"
      - "7268:7268"
    env_file:
      - .env
    volumes:
      - ~/.aspnet/https:/https:ro

  
  postgres:
    image: postgres
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - supfileback_default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file:
      - .env

  azureblobstorage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    stdin_open: true
    tty: true
    volumes:
      - blobstorage_data:/data
    networks:
      - supfileback_default
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '127.0.0.1:5001:80'    # Web interface
    volumes:
      - smtp4dev-data:/smtp4dev
    networks:
      - supfileback_default
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  postgres_data:
  blobstorage_data:
  smtp4dev-data:

networks:
  supfileback_default:
    driver: bridge