// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="ApplicationUser" />
    /// </summary>
    public partial class ApplicationUserMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.ApplicationUser>
    {
        /// <summary>
        /// Configures the entity of type <see cref="ApplicationUser" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<
                SupFile.Back.Core.Entities.ApplicationUser> builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("User", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.IdentityUserId)
                .HasColumnName("IdentityUserId")
                .HasColumnType("uuid");

            builder.Property(t => t.Username)
                .IsRequired()
                .HasColumnName("Username")
                .HasColumnType("varchar(50)")
                .HasMaxLength(50);
            
            builder.Property(t => t.FirstName)
                .IsRequired()
                .HasColumnName("FirstName")
                .HasColumnType("varchar(50)")
                .HasMaxLength(50);

            builder.Property(t => t.LastName)
                .HasColumnName("LastName")
                .HasColumnType("varchar(50)")
                .HasMaxLength(50);

            builder.Property(t => t.Language)
                .IsRequired()
                .HasColumnName("Language")
                .HasColumnType("int");

            // relationships
            builder.HasOne(t => t.IdentityUser)
                .WithOne(t => t.ApplicationUser)
                .HasForeignKey<ApplicationUser>(d => d.IdentityUserId)
                .HasConstraintName("FK_User_ApplicationUser")
                .OnDelete(DeleteBehavior.Cascade);

            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.UserGeneralRole" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.UserGeneralRole" /></summary>
            public const string Name = "UserGeneralRole";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.UserGeneralRole.UserId" /></summary>
            public const string UserId = "UserId";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.UserGeneralRole.GeneralRoleId" /></summary>
            public const string GeneralRoleId = "GeneralRoleId";
        }

        #endregion
    }
}