// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.Directory" />
    /// </summary>
    public partial class DirectoryMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.Directory>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.Directory" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.Directory>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("Directory", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.OwnerId)
                .IsRequired()
                .HasColumnName("OwnerId")
                .HasColumnType("int");
            
            builder.Property(t => t.ParentId)
                .HasColumnName("ParentId")
                .HasColumnType("int");
            

            // relationships
            builder.HasOne(t => t.OwnerApplicationUserDirectory)
                .WithMany(t => t.OwnerDirectories)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("Directories_User_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.ParentDirectory)
                .WithMany(t => t.ParentDirectories)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("DirectoryParent___fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.SetNull);

            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.Directory" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.Directory" /></summary>
            public const string Name = "Directory";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Directory.Id" /></summary>
            public const string Id = "Id";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Directory.Name" /></summary>
            public const string Name = "Name";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Directory.OwnerId" /></summary>
            public const string OwnerId = "OwnerId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Directory.ParentId" /></summary>
            public const string ParentId = "ParentId";
        }

        #endregion
    }
}