// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.File" />
    /// </summary>
    public partial class FileMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.File>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.File" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.File>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("File", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.Extension)
                .IsRequired()
                .HasColumnName("Extension")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.Size)
                .IsRequired()
                .HasColumnName("Size")
                .HasColumnType("bigint");
            
            builder.Property(t => t.Path)
                .IsRequired()
                .HasColumnName("Path")
                .HasColumnType("varchar(1024)")
                .HasMaxLength(1024);
            
            builder.Property(t => t.IsActive)
                .IsRequired()
                .HasColumnName("IsActive")
                .HasColumnType("boolean");
            
            builder.Property(t => t.CreatedDate)
                .IsRequired()
                .HasColumnName("CreatedDate")
                .HasColumnType("timestamp");
            
            builder.Property( t => t.DirectoryId)
                .HasColumnName("DirectoryId")
                .HasColumnType("int");
            
            builder.Property(t => t.OwnerId)
                .IsRequired()
                .HasColumnName("OwnerId")
                .HasColumnType("int");
            

            // relationships
            builder.HasOne(t => t.FileDirectory)
                .WithMany(t => t.Files)
                .HasForeignKey(d => d.DirectoryId)
                .HasConstraintName("Files_Directory_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.OwnerApplicationUserFile)
                .WithMany(t => t.OwnerFile)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("Files_User_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);

            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.File" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.File" /></summary>
            public const string Name = "File";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.Id" /></summary>
            public const string Id = "Id";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.Name" /></summary>
            public const string Name = "Name";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.Extension" /></summary>
            public const string Extension = "Extension";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.Size" /></summary>
            public const string Size = "Size";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.Path" /></summary>
            public const string Path = "Path";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.IsActive" /></summary>
            public const string IsActive = "IsActive";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.CreatedDate" /></summary>
            public const string CreatedDate = "CreatedDate";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.DirectoryId" /></summary>
            public const string DirectoryId = "DirectoryId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.File.OwnerId" /></summary>
            public const string OwnerId = "OwnerId";
        }

        #endregion
    }
}