// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.Folder" />
    /// </summary>
    public partial class FolderMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.Folder>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.Folder" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.Folder>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("Folder", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.OwnerId)
                .IsRequired()
                .HasColumnName("OwnerId")
                .HasColumnType("int");
            
            builder.Property(t => t.ParentId)
                .HasColumnName("ParentId")
                .HasColumnType("int");
            
            builder.Property(t => t.IsActive)
                .IsRequired()
                .HasColumnName("IsActive")
                .HasColumnType("boolean");
            

            // relationships
            builder.HasOne(t => t.OwnerApplicationUserFolder)
                .WithMany(t => t.OwnerFolders)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("Folders_User_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.ParentFolder)
                .WithMany(t => t.ParentFolders)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FolderParent___fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.SetNull);

            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.Folder" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.Folder" /></summary>
            public const string Name = "Folder";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Folder.Id" /></summary>
            public const string Id = "Id";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Folder.Name" /></summary>
            public const string Name = "Name";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Folder.OwnerId" /></summary>
            public const string OwnerId = "OwnerId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Folder.ParentId" /></summary>
            public const string ParentId = "ParentId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Folder.IsActive" /></summary>
            public const string IsActive = "IsActive";
        }

        #endregion
    }
}