// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.Link" />
    /// </summary>
    public partial class LinkMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.Link>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.Link" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.Link>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("Link", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.Token)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("text");
            
            builder.Property(t => t.Type)
                .IsRequired()
                .HasColumnName("Type")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.ExpirationDate)
                .HasColumnName("ExpirationDate")
                .HasColumnType("timestamp");
            
            builder.Property(t => t.ShareMediaId)
                .IsRequired()
                .HasColumnName("ShareMediaId")
                .HasColumnType("int");
            
            builder.Property(t => t.ShareFolderId)
                .IsRequired()
                .HasColumnName("ShareFolderId")
                .HasColumnType("int");
            
            // relationships
            builder.HasOne(t => t.ShareLinkFolder)
                .WithMany(t => t.Links)
                .HasForeignKey(d => d.ShareFolderId)
                .HasConstraintName("Link_Folder_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.ShareLinkFile)
                .WithMany(t => t.Links)
                .HasForeignKey(d => d.ShareMediaId)
                .HasConstraintName("Link_File_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.Link" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.Link" /></summary>
            public const string Name = "Link";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.Id" /></summary>
            public const string Id = "Id";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.Token" /></summary>
            public const string Token = "Token";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.Type" /></summary>
            public const string Type = "Type";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.ExpirationDate" /></summary>
            public const string ExpirationDate = "ExpirationDate";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.ShareMediaId" /></summary>
            public const string ShareFileId = "ShareMediaId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Link.ShareFolderId" /></summary>
            public const string ShareFolderId = "ShareFolderId";
        }

        #endregion
    }
}