// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.Media" />
    /// </summary>
    public partial class MediaMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.Media>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.Media" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.Media>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("Media", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();

            builder.Property(t => t.Name)
                .IsRequired()
                .HasColumnName("Name")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.Extension)
                .IsRequired()
                .HasColumnName("Extension")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.Size)
                .IsRequired()
                .HasColumnName("Size")
                .HasColumnType("bigint");
            
            builder.Property(t => t.IsActive)
                .IsRequired()
                .HasColumnName("IsActive")
                .HasColumnType("boolean");
            
            builder.Property(t => t.CreatedDate)
                .IsRequired()
                .HasColumnName("CreatedDate")
                .HasColumnType("timestamp");
            
            builder.Property( t => t.FolderId)
                .HasColumnName("FolderId")
                .HasColumnType("int");
            
            builder.Property(t => t.OwnerId)
                .IsRequired()
                .HasColumnName("OwnerId")
                .HasColumnType("int");
            

            // relationships
            builder.HasOne(t => t.Folder)
                .WithMany(t => t.Medias)
                .HasForeignKey(d => d.FolderId)
                .HasConstraintName("Medias_Folder_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.OwnerApplicationUser)
                .WithMany(t => t.OwnerMedias)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("Medias_User_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);

            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.Media" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.Media" /></summary>
            public const string Name = "Media";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.Id" /></summary>
            public const string Id = "Id";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.Name" /></summary>
            public const string Name = "Name";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.Extension" /></summary>
            public const string Extension = "Extension";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.Size" /></summary>
            public const string Size = "Size";

            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.IsActive" /></summary>
            public const string IsActive = "IsActive";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.CreatedDate" /></summary>
            public const string CreatedDate = "CreatedDate";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.FolderId" /></summary>
            public const string FolderId = "FolderId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Media.OwnerId" /></summary>
            public const string OwnerId = "OwnerId";
        }

        #endregion
    }
}