// <auto-generated />

namespace SupFile.Back.Data.Mapping
{
    /// <summary>
    /// Allows configuration for an entity type <see cref="SupFile.Back.Core.Entities.Share" />
    /// </summary>
    public partial class ShareMap
        : IEntityTypeConfiguration<SupFile.Back.Core.Entities.Share>
    {
        /// <summary>
        /// Configures the entity of type <see cref="SupFile.Back.Core.Entities.Share" />
        /// </summary>
        /// <param name="builder">The builder to be used to configure the entity type.</param>
        public void Configure(
            Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<SupFile.Back.Core.Entities.Share>
                builder)
        {
            #region Generated Configure

            // table
            builder.ToTable("Share", "public");

            // key
            builder.HasKey(t => t.Id);

            // properties
            builder.Property(t => t.Id)
                .IsRequired()
                .HasColumnName("Id")
                .HasColumnType("int")
                .ValueGeneratedOnAdd();
            
            builder.Property(t => t.Permission)
                .IsRequired()
                .HasColumnName("Permission")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.UserId)
                .IsRequired()
                .HasColumnName("UserId")
                .HasColumnType("int");
            
            builder.Property(t => t.Type)
                .IsRequired()
                .HasColumnName("Type")
                .HasColumnType("varchar(255)")
                .HasMaxLength(255);
            
            builder.Property(t => t.ShareFileId)
                .HasColumnName("ShareFileId")
                .HasColumnType("int");
            
            builder.Property(t => t.ShareDirectoryId)
                .HasColumnName("ShareDirectoryId")
                .HasColumnType("int");
            
            // relationships
            
            builder.HasOne(t => t.ShareUser)
                .WithMany(t => t.OwnedShares)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("Shares_User_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.ShareDirectory)
                .WithMany(t => t.Shares)
                .HasForeignKey(d => d.ShareDirectoryId)
                .HasConstraintName("Share_Directory_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            builder.HasOne(t => t.ShareFile)
                .WithMany(t => t.Shares)
                .HasForeignKey(d => d.ShareFileId)
                .HasConstraintName("Share_File_Id_fk")
                .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Cascade);
            
            #endregion
        }

        #region Generated Constants

        public readonly struct Table
        {
            /// <summary>Table Schema name constant for entity <see cref="SupFile.Back.Core.Entities.Share" /></summary>
            public const string Schema = "public";

            /// <summary>Table Name constant for entity <see cref="SupFile.Back.Core.Entities.Share" /></summary>
            public const string Name = "Share";
        }

        public readonly struct Columns
        {
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.Id" /></summary>
            public const string Id = "Id";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.Permission" /></summary>
            public const string Permission = "Permission";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.UserId" /></summary>
            public const string UserId = "UserId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.Type" /></summary>
            public const string Type = "Type";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.ShareFileId" /></summary>
            public const string ShareFileId = "ShareFileId";
            
            /// <summary>Column Name constant for property <see cref="SupFile.Back.Core.Entities.Share.ShareDirectoryId" /></summary>
            public const string ShareDirectoryId = "ShareDirectoryId";
        }

        #endregion
    }
}