<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SupFile.Back.Core\SupFile.Back.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="3.16.0"/>
        <PackageReference Include="Gridify.EntityFramework" Version="2.16.1"/>
        <PackageReference Include="Mapster" Version="7.4.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql" Version="9.0.2"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0"/>
        <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Migrations\"/>
    </ItemGroup>

</Project>
