// <auto-generated />

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using SupFile.Back.Core.Entities.Auth;
using Directory = SupFile.Back.Core.Entities.Directory;
using File = SupFile.Back.Core.Entities.File;

namespace SupFile.Back.Data.Context;

/// <summary>
///     A <see cref="DbContext" /> instance represents a session with the database and can be used to query and save
///     instances of entities.
/// </summary>
public class SupFileContext : IdentityDbContext<
    ApplicationUser,
    ApplicationRole,
    int,
    IdentityUserClaim<int>,
    ApplicationUserRole,
    IdentityUserLogin<int>,
    IdentityRoleClaim<int>,
    IdentityUserToken<int>>
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="SupFileContext" /> class.
    /// </summary>
    /// <param name="options">The options to be used by this <see cref="DbContext" />.</param>
    public SupFileContext(DbContextOptions<SupFileContext> options)
        : base(options)
    {
    }

    /// <summary>
    ///     Configure the model that was discovered from the entity types exposed in
    ///     <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on this context.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        #region Generated Configuration

        modelBuilder.ApplyConfiguration(new DirectoryMap());
        modelBuilder.ApplyConfiguration(new FileMap());
        modelBuilder.ApplyConfiguration(new ShareMap());
        modelBuilder.ApplyConfiguration(new LinkMap());

        #endregion
        
        modelBuilder.Entity<ApplicationUser>(entity => entity.ToTable("User"));
        modelBuilder.Entity<ApplicationRole>(entity => entity.ToTable("Role"));
        modelBuilder.Entity<ApplicationUserRole>(entity => entity.ToTable("UserRole"));
        modelBuilder.Entity<IdentityUserClaim<int>>(entity => entity.ToTable("Claim"));
        modelBuilder.Entity<IdentityRoleClaim<int>>(entity => entity.ToTable("RoleClaim"));
        modelBuilder.Entity<IdentityUserLogin<int>>(entity => entity.ToTable("UserLogin"));
        modelBuilder.Entity<IdentityUserToken<int>>(entity => entity.ToTable("UserToken"));
    }

    #region Generated Properties

    public virtual DbSet<Directory> Directories { get; set; }
    public virtual DbSet<File> Files { get; set; }
    public virtual DbSet<Link> Links { get; set; }
    public virtual DbSet<Share> Shares { get; set; }
    
    #endregion
}
