// <auto-generated />

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using SupFile.Back.Core.Entities.Auth;

namespace SupFile.Back.Data.Context;

/// <summary>
///     A <see cref="DbContext" /> instance represents a session with the database and can be used to query and save
///     instances of entities.
/// </summary>
public class SupFileContext : IdentityDbContext<AuthIdentityUser, IdentityRole<Guid>, Guid>
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="SupFileContext" /> class.
    /// </summary>
    /// <param name="options">The options to be used by this <see cref="DbContext" />.</param>
    public SupFileContext(DbContextOptions<SupFileContext> options)
        : base(options)
    {
    }

    /// <summary>
    ///     Configure the model that was discovered from the entity types exposed in
    ///     <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on this context.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        #region Generated Configuration

        modelBuilder.ApplyConfiguration(new ApplicationUserMap());
        modelBuilder.ApplyConfiguration(new FolderMap());
        modelBuilder.ApplyConfiguration(new MediaMap());
        modelBuilder.ApplyConfiguration(new ShareMap());
        modelBuilder.ApplyConfiguration(new LinkMap());

        #endregion
    }

    #region Generated Properties

    /// <summary>
    ///     Gets or sets the <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save
    ///     instances of <see cref="ApplicationUser" />.
    /// </summary>
    /// <value>
    ///     The <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> that can be used to query and save instances of
    ///     <see cref="ApplicationUser" />.
    /// </value>
    public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; } = null!;

    #endregion
}
