//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupFile.Back.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumDescriptionResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescriptionResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SupFile.Back.Resources.EnumDescriptionResource", typeof(EnumDescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UserStatus_Away {
            get {
                return ResourceManager.GetString("UserStatus_Away", resourceCulture);
            }
        }
        
        public static string UserStatus_Busy {
            get {
                return ResourceManager.GetString("UserStatus_Busy", resourceCulture);
            }
        }
        
        public static string UserStatus_Offline {
            get {
                return ResourceManager.GetString("UserStatus_Offline", resourceCulture);
            }
        }
        
        public static string UserStatus_Invisible {
            get {
                return ResourceManager.GetString("UserStatus_Invisible", resourceCulture);
            }
        }
        
        public static string UserStatus_Online {
            get {
                return ResourceManager.GetString("UserStatus_Online", resourceCulture);
            }
        }
        
        public static string UserTheme_Light {
            get {
                return ResourceManager.GetString("UserTheme_Light", resourceCulture);
            }
        }
        
        public static string UserTheme_Dark {
            get {
                return ResourceManager.GetString("UserTheme_Dark", resourceCulture);
            }
        }
        
        public static string WorkspaceVisibility_Public {
            get {
                return ResourceManager.GetString("WorkspaceVisibility_Public", resourceCulture);
            }
        }
        
        public static string WorkspaceVisibility_Private {
            get {
                return ResourceManager.GetString("WorkspaceVisibility_Private", resourceCulture);
            }
        }
        
        public static string ChannelVisibility_Public {
            get {
                return ResourceManager.GetString("ChannelVisibility_Public", resourceCulture);
            }
        }
        
        public static string ChannelVisibility_Private {
            get {
                return ResourceManager.GetString("ChannelVisibility_Private", resourceCulture);
            }
        }
        
        public static string UserLanguage_English {
            get {
                return ResourceManager.GetString("UserLanguage_English", resourceCulture);
            }
        }
        
        public static string UserLanguage_French {
            get {
                return ResourceManager.GetString("UserLanguage_French", resourceCulture);
            }
        }
        
        public static string NotificationType_Text {
            get {
                return ResourceManager.GetString("NotificationType_Text", resourceCulture);
            }
        }
        
        public static string NotificationType_Message {
            get {
                return ResourceManager.GetString("NotificationType_Message", resourceCulture);
            }
        }
        
        public static string NotificationType_Other {
            get {
                return ResourceManager.GetString("NotificationType_Other", resourceCulture);
            }
        }
        
        public static string AttachmentType_Image {
            get {
                return ResourceManager.GetString("AttachmentType_Image", resourceCulture);
            }
        }
        
        public static string AttachmentType_Video {
            get {
                return ResourceManager.GetString("AttachmentType_Video", resourceCulture);
            }
        }
        
        public static string AttachmentType_Audio {
            get {
                return ResourceManager.GetString("AttachmentType_Audio", resourceCulture);
            }
        }
        
        public static string AttachmentType_File {
            get {
                return ResourceManager.GetString("AttachmentType_File", resourceCulture);
            }
        }
        
        public static string AttachmentType_Link {
            get {
                return ResourceManager.GetString("AttachmentType_Link", resourceCulture);
            }
        }
        
        public static string PermissionActions_ReadAll {
            get {
                return ResourceManager.GetString("PermissionActions_ReadAll", resourceCulture);
            }
        }
        
        public static string PermissionActions_ReadOne {
            get {
                return ResourceManager.GetString("PermissionActions_ReadOne", resourceCulture);
            }
        }
        
        public static string PermissionActions_CreateOne {
            get {
                return ResourceManager.GetString("PermissionActions_CreateOne", resourceCulture);
            }
        }
        
        public static string PermissionActions_UpdateOne {
            get {
                return ResourceManager.GetString("PermissionActions_UpdateOne", resourceCulture);
            }
        }
        
        public static string PermissionActions_DeleteOne {
            get {
                return ResourceManager.GetString("PermissionActions_DeleteOne", resourceCulture);
            }
        }
        
        public static string PermissionActions_UpdateOwn {
            get {
                return ResourceManager.GetString("PermissionActions_UpdateOwn", resourceCulture);
            }
        }
        
        public static string PermissionActions_DeleteOwn {
            get {
                return ResourceManager.GetString("PermissionActions_DeleteOwn", resourceCulture);
            }
        }
        
        public static string AttachmentType_ProfilePicture {
            get {
                return ResourceManager.GetString("AttachmentType_ProfilePicture", resourceCulture);
            }
        }
    }
}
