//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupFile.Back.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsRes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsRes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SupFile.Back.Resources.ErrorsRes", typeof(ErrorsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BadRequest_Title {
            get {
                return ResourceManager.GetString("BadRequest_Title", resourceCulture);
            }
        }
        
        public static string Unauthorize_Title {
            get {
                return ResourceManager.GetString("Unauthorize_Title", resourceCulture);
            }
        }
        
        public static string Unauthorize_Detail {
            get {
                return ResourceManager.GetString("Unauthorize_Detail", resourceCulture);
            }
        }
        
        public static string Null_Value_Error_Detail {
            get {
                return ResourceManager.GetString("Null_Value_Error_Detail", resourceCulture);
            }
        }
        
        public static string Null_Value_Error_Title {
            get {
                return ResourceManager.GetString("Null_Value_Error_Title", resourceCulture);
            }
        }
        
        public static string Null_Field_Error_Detail {
            get {
                return ResourceManager.GetString("Null_Field_Error_Detail", resourceCulture);
            }
        }
        
        public static string UserNotFound_Title {
            get {
                return ResourceManager.GetString("UserNotFound_Title", resourceCulture);
            }
        }
        
        public static string UserNotFound_Detail {
            get {
                return ResourceManager.GetString("UserNotFound_Detail", resourceCulture);
            }
        }
        
        public static string RefreshTokenExpired_Title {
            get {
                return ResourceManager.GetString("RefreshTokenExpired_Title", resourceCulture);
            }
        }
        
        public static string RefreshTokenExpired_Detail {
            get {
                return ResourceManager.GetString("RefreshTokenExpired_Detail", resourceCulture);
            }
        }
        
        public static string CannotBeOwnParent_Title {
            get {
                return ResourceManager.GetString("CannotBeOwnParent_Title", resourceCulture);
            }
        }
        
        public static string CannotBeOwnParent_Detail {
            get {
                return ResourceManager.GetString("CannotBeOwnParent_Detail", resourceCulture);
            }
        }
        
        public static string ParentFolderNotOwnedByUser_Title {
            get {
                return ResourceManager.GetString("ParentFolderNotOwnedByUser_Title", resourceCulture);
            }
        }
        
        public static string ParentFolderNotOwnedByUser_Detail {
            get {
                return ResourceManager.GetString("ParentFolderNotOwnedByUser_Detail", resourceCulture);
            }
        }
        
        public static string EmailAlreadyExist_Title {
            get {
                return ResourceManager.GetString("EmailAlreadyExist_Title", resourceCulture);
            }
        }
        
        public static string EmailAlreadyExist_Detail {
            get {
                return ResourceManager.GetString("EmailAlreadyExist_Detail", resourceCulture);
            }
        }
        
        public static string UsernameAlreadyExist_Title {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist_Title", resourceCulture);
            }
        }
        
        public static string UsernameAlreadyExist_Detail {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist_Detail", resourceCulture);
            }
        }
        
        public static string InvalidEmailOrPassword_Title {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword_Title", resourceCulture);
            }
        }
        
        public static string InvalidEmailOrPassword_Detail {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword_Detail", resourceCulture);
            }
        }
        
        public static string EmailNotConfirmed_Title {
            get {
                return ResourceManager.GetString("EmailNotConfirmed_Title", resourceCulture);
            }
        }
        
        public static string EmailNotConfirmed_Detail {
            get {
                return ResourceManager.GetString("EmailNotConfirmed_Detail", resourceCulture);
            }
        }
        
        public static string Entity_Not_Found_Title {
            get {
                return ResourceManager.GetString("Entity_Not_Found_Title", resourceCulture);
            }
        }
        
        public static string Entity_Not_Found_Detail {
            get {
                return ResourceManager.GetString("Entity_Not_Found_Detail", resourceCulture);
            }
        }
        
        public static string Entity_Not_Found_With_Id_Title {
            get {
                return ResourceManager.GetString("Entity_Not_Found_With_Id_Title", resourceCulture);
            }
        }
        
        public static string Entity_Not_Found_With_Id_Detail {
            get {
                return ResourceManager.GetString("Entity_Not_Found_With_Id_Detail", resourceCulture);
            }
        }
        
        public static string FileNotFound_Title {
            get {
                return ResourceManager.GetString("FileNotFound_Title", resourceCulture);
            }
        }
        
        public static string FileNotFound_Detail {
            get {
                return ResourceManager.GetString("FileNotFound_Detail", resourceCulture);
            }
        }
        
        public static string ExtensionDoesNotStartWithADot_Title {
            get {
                return ResourceManager.GetString("ExtensionDoesNotStartWithADot_Title", resourceCulture);
            }
        }
        
        public static string ExtensionDoesNotStartWithADot_Detail {
            get {
                return ResourceManager.GetString("ExtensionDoesNotStartWithADot_Detail", resourceCulture);
            }
        }
        
        public static string EmptyContent_Title {
            get {
                return ResourceManager.GetString("EmptyContent_Title", resourceCulture);
            }
        }
        
        public static string EmptyContent_Detail {
            get {
                return ResourceManager.GetString("EmptyContent_Detail", resourceCulture);
            }
        }
        
        public static string FileAlreadyExists_Title {
            get {
                return ResourceManager.GetString("FileAlreadyExists_Title", resourceCulture);
            }
        }
        
        public static string FileAlreadyExists_Detail {
            get {
                return ResourceManager.GetString("FileAlreadyExists_Detail", resourceCulture);
            }
        }
        
        public static string InvalidType_Title {
            get {
                return ResourceManager.GetString("InvalidType_Title", resourceCulture);
            }
        }
        
        public static string InvalidType_Detail {
            get {
                return ResourceManager.GetString("InvalidType_Detail", resourceCulture);
            }
        }
        
        public static string CannotAcceptOwnShareLink_Title {
            get {
                return ResourceManager.GetString("CannotAcceptOwnShareLink_Title", resourceCulture);
            }
        }
        
        public static string CannotAcceptOwnShareLink_Detail {
            get {
                return ResourceManager.GetString("CannotAcceptOwnShareLink_Detail", resourceCulture);
            }
        }
        
        public static string LinkExpired_Title {
            get {
                return ResourceManager.GetString("LinkExpired_Title", resourceCulture);
            }
        }
        
        public static string LinkExpired_Detail {
            get {
                return ResourceManager.GetString("LinkExpired_Detail", resourceCulture);
            }
        }
        
        public static string InvalidSortField_Title {
            get {
                return ResourceManager.GetString("InvalidSortField_Title", resourceCulture);
            }
        }
        
        public static string InvalidSortField_Detail {
            get {
                return ResourceManager.GetString("InvalidSortField_Detail", resourceCulture);
            }
        }
        
        public static string NoChangesOnDelete_Title {
            get {
                return ResourceManager.GetString("NoChangesOnDelete_Title", resourceCulture);
            }
        }
        
        public static string NoChangesOnDelete_Detail {
            get {
                return ResourceManager.GetString("NoChangesOnDelete_Detail", resourceCulture);
            }
        }
        
        public static string Internal_Server_Error_Title {
            get {
                return ResourceManager.GetString("Internal_Server_Error_Title", resourceCulture);
            }
        }
        
        public static string Internal_Server_Error_Detail {
            get {
                return ResourceManager.GetString("Internal_Server_Error_Detail", resourceCulture);
            }
        }
        
        public static string Validation_Title {
            get {
                return ResourceManager.GetString("Validation_Title", resourceCulture);
            }
        }
        
        public static string Validation_Detail {
            get {
                return ResourceManager.GetString("Validation_Detail", resourceCulture);
            }
        }
        
        public static string InvalidTypeProvided_Title {
            get {
                return ResourceManager.GetString("InvalidTypeProvided_Title", resourceCulture);
            }
        }
        
        public static string InvalidTypeProvided_Detail {
            get {
                return ResourceManager.GetString("InvalidTypeProvided_Detail", resourceCulture);
            }
        }
        
        public static string NoMediaFound_Title {
            get {
                return ResourceManager.GetString("NoMediaFound_Title", resourceCulture);
            }
        }
        
        public static string NoMediaFound_Detail {
            get {
                return ResourceManager.GetString("NoMediaFound_Detail", resourceCulture);
            }
        }
        
        public static string NoFolderFound_Title {
            get {
                return ResourceManager.GetString("NoFolderFound_Title", resourceCulture);
            }
        }
        
        public static string NoFolderFound_Detail {
            get {
                return ResourceManager.GetString("NoFolderFound_Detail", resourceCulture);
            }
        }
        
        public static string EmptyBin_Title {
            get {
                return ResourceManager.GetString("EmptyBin_Title", resourceCulture);
            }
        }
        
        public static string EmptyBin_Detail {
            get {
                return ResourceManager.GetString("EmptyBin_Detail", resourceCulture);
            }
        }
        
        public static string BinItem_Title {
            get {
                return ResourceManager.GetString("BinItem_Title", resourceCulture);
            }
        }
        
        public static string BinItem_Detail {
            get {
                return ResourceManager.GetString("BinItem_Detail", resourceCulture);
            }
        }
        
        public static string InvalidStorageSizeGroupBy_Title {
            get {
                return ResourceManager.GetString("InvalidStorageSizeGroupBy_Title", resourceCulture);
            }
        }
        
        public static string InvalidStorageSizeGroupBy_Detail {
            get {
                return ResourceManager.GetString("InvalidStorageSizeGroupBy_Detail", resourceCulture);
            }
        }
        
        public static string InvalidUniqueId_Title {
            get {
                return ResourceManager.GetString("InvalidUniqueId_Title", resourceCulture);
            }
        }
        
        public static string InvalidUniqueId_Detail {
            get {
                return ResourceManager.GetString("InvalidUniqueId_Detail", resourceCulture);
            }
        }
        
        public static string IncorrectPassword_Title {
            get {
                return ResourceManager.GetString("IncorrectPassword_Title", resourceCulture);
            }
        }
        
        public static string IncorrectPassword_Detail {
            get {
                return ResourceManager.GetString("IncorrectPassword_Detail", resourceCulture);
            }
        }
        
        public static string PasswordDoesntMatch_Title {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch_Title", resourceCulture);
            }
        }
        
        public static string PasswordDoesntMatch_Detail {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch_Detail", resourceCulture);
            }
        }
        
        public static string AspNetUserNotFound_Title {
            get {
                return ResourceManager.GetString("AspNetUserNotFound_Title", resourceCulture);
            }
        }
        
        public static string AspNetUserNotFound_Detail {
            get {
                return ResourceManager.GetString("AspNetUserNotFound_Detail", resourceCulture);
            }
        }
        
        public static string CannotAddInSoftDeleted_Title {
            get {
                return ResourceManager.GetString("CannotAddInSoftDeleted_Title", resourceCulture);
            }
        }
        
        public static string CannotAddInSoftDeleted_Detail {
            get {
                return ResourceManager.GetString("CannotAddInSoftDeleted_Detail", resourceCulture);
            }
        }
        
        public static string CannotDownloadSoftDeleted_Title {
            get {
                return ResourceManager.GetString("CannotDownloadSoftDeleted_Title", resourceCulture);
            }
        }
        
        public static string CannotDownloadSoftDeleted_Detail {
            get {
                return ResourceManager.GetString("CannotDownloadSoftDeleted_Detail", resourceCulture);
            }
        }
        
        public static string UserNameNotFound_Title {
            get {
                return ResourceManager.GetString("UserNameNotFound_Title", resourceCulture);
            }
        }
        
        public static string UserNameNotFound_Detail {
            get {
                return ResourceManager.GetString("UserNameNotFound_Detail", resourceCulture);
            }
        }
        
        public static string InvalideProfilePictureType_Title {
            get {
                return ResourceManager.GetString("InvalideProfilePictureType_Title", resourceCulture);
            }
        }
        
        public static string InvalideProfilePictureType_Detail {
            get {
                return ResourceManager.GetString("InvalideProfilePictureType_Detail", resourceCulture);
            }
        }
        
        public static string MediaIsDeleted_Title {
            get {
                return ResourceManager.GetString("MediaIsDeleted_Title", resourceCulture);
            }
        }
        
        public static string MediaIsDeleted_Detail {
            get {
                return ResourceManager.GetString("MediaIsDeleted_Detail", resourceCulture);
            }
        }
        
        public static string StorageLimitExceeded_Title {
            get {
                return ResourceManager.GetString("StorageLimitExceeded_Title", resourceCulture);
            }
        }
        
        public static string StorageLimitExceeded_Detail {
            get {
                return ResourceManager.GetString("StorageLimitExceeded_Detail", resourceCulture);
            }
        }
    }
}
